import React from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/footer'
import List from '../Components/list'
import tachyons from 'tachyons/css/tachyons.css'
import styles from '../styles/Home.module.css'
import logo from '../Components/assets/logo.svg'

export default function lost() {
    return (
        <div className="w-100 vh-100">
            <Head>
                <title>Directorio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <nav className="pa2 flex justify-between bg-black bb b--white-10 ">
                    <div className="flex items-center">
                        <Image src={logo} alt="logo" width={40} heigth={40} />
                        <p className="b roboto dn db-m db-l">FOTOGRAFOSDEPUERTORICO</p>
                    </div>
                    <div className="  pa2 flex justify-around ">

                        <a href="join" className="ba tc pa2 mr3 pointer flex items-center">EDITAR</a>
                        <a href="about" className="ba tc pa2 pinter flex items-center">NOSOTROS</a>
                    </div>
                </nav>
            </header>


            <main className="center tc  mw7 vh-75 flex flex-wrap items-center justify-center">
                <div>
                    <p className="w-100 f2 i">（ミ￣ー￣ミ）| Por aquí no hay nada.</p>
                    <Link href="/" className="light-purple underline">←regresar</Link>
                </div>

            </main>

            <footer className={styles.footer}>
                <Footer />
            </footer>
        </div>
    )
}
